name: Custom Flutter Build

on:
  workflow_dispatch:
    inputs:
      upload-tag:
        description: Release tag used for generated artifacts
        required: true
        default: custom
      embedded-id-server:
        description: Embedded ID server, e.g. 222869.xyz:21116
        required: true
        default: 222869.xyz:21116
      embedded-relay-server:
        description: Embedded relay server, e.g. 222869.xyz:21117
        required: true
        default: 222869.xyz:21117
      embedded-api-server:
        description: Embedded API server, e.g. http://222869.xyz:21114
        required: true
        default: http://222869.xyz:21114
      embedded-key:
        description: Embedded RustDesk public key
        required: true
        default: 0123456789

jobs:
  run-custom-flutter-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag }}
      embedded-id-server: ${{ inputs.embedded-id-server }}
      embedded-relay-server: ${{ inputs.embedded-relay-server }}
      embedded-api-server: ${{ inputs.embedded-api-server }}
      embedded-key: ${{ inputs.embedded-key }}
      build-windows-flutter: true
      build-windows-sciter: false
      build-ios: false
      build-macos: false
      publish-unsigned: false
      build-android: false
      build-android-universal: false
      build-linux: true
      linux-build-matrix: >-
        [{"arch":"x86_64","target":"x86_64-unknown-linux-gnu","distro":"ubuntu18.04","on":"ubuntu-22.04","deb_arch":"amd64","vcpkg-triplet":"x64-linux"}]
      build-linux-rpm: false
      build-linux-arch-package: false
      build-linux-sciter: false
      build-appimage: false
      build-flatpak: false
      build-web: false
